### ISSUE TITLE
Fails on MWE: Cannot determine Numba type of <class 'function'>

### ISSUE THREAD

**Issue by rmusab** [mortacious/numba-kdtree#12]
The following MWE causes the Numba to fail:

```
import numpy as np
from numba import njit
from numba_kdtree import KDTree

@njit
def numba_function_with_kdtree(data):
    kdtree = KDTree(data, leafsize=10)
    for i in range(5):
        distances, indices, _ = kdtree.query(data[i], k=30)
        # Use the computed neighbors
        print(distances, indices)

data = np.random.random(3_000).reshape(-1, 3)
numba_function_with_kdtree(data)
```
with the error
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'KDTree': Cannot determine Numba type of <class 'function'>
```

**Comment by mortacious** [comment]
In the current version it was indeed not possible for `KDTree` to be called from within a numba compiled function. The created object instead had to be passed into the function as an argument. 
I've just realized, that this is actually no longer required so I've just published a new release (0.1.7) that removes this restriction.

**Comment by rmusab** [comment]
> In the current version it was indeed not possible for `KDTree` to be called from within a numba compiled function. The created object instead had to be passed into the function as an argument. I've just realized, that this is actually no longer required so I've just published a new release (0.1.7) that removes this restriction.

Thank you! I have upgraded to version 0.1.7, but the same error still persists.
